[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gsheets-orm"
version = "0.1.7"
description = "A lightweight Object-Relational Mapper (ORM) backed by Google Sheets"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "FarzanFrost" }]
requires-python = ">=3.9"
dependencies = [
    "gspread>=5.10.0",
    "google-auth>=2.22.0",
    "python-dotenv>=1.0.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/FarzanFrost/gsheets-orm-repo"

[tool.setuptools.packages.find]
exclude = ["tests*", "docs*"]
